name: Sync Multiple Goozapp Streams

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [external-trigger, sync-trigger]

jobs:
  sync-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Sync Script
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
        API_URL_GOOZAPP: ${{ secrets.API_URL_GOOZAPP }}
        API_URL_STREAMS_CENTER: ${{ secrets.API_URL_STREAMS_CENTER }}
        API_URL_FAWNA: ${{ secrets.API_URL_FAWNA }}
        API_URL_ROXI: ${{ secrets.API_URL_ROXI }}
        API_URL_CR7: ${{ secrets.API_URL_CR7 }}
        API_URL_BING: ${{ secrets.API_URL_BING }}
        API_URL_FLUXY: ${{ secrets.API_URL_FLUXY }}
        API_URL_MAIN_STREAM: ${{ secrets.API_URL_MAIN_STREAM }}
      run: python sync_script.py
